'use strict';
// Where this machine's copy of the agent lives, recorded in the data dir so
// nothing outside it has to embed a path that can move.
//
// A plugin install lands in a VERSIONED directory
// (~/.claude/plugins/cache/<marketplace>/<plugin>/<version>/), so every update
// is a new root and the old one is eventually collected. A clone install moves
// whenever someone reorganizes their disk. Either way, a logon task that hard-
// codes today's path is a silent failure tomorrow: the watcher just never
// starts, and the UI looks frozen while hooks keep spooling.
//
// So autostart points at a stable launcher in the data dir, the launcher reads
// this file, and whoever runs (hook-forward on SessionStart, or any cli.js
// command) keeps it current.
const fs = require('fs');
const path = require('path');
const { paths, ensureDirs } = require('./paths');
const { readJson, writeJsonAtomic } = require('./util/jsonfile');

// <repo-or-plugin-root>/src/agent-root.js → the root itself.
const AGENT_ROOT = path.resolve(__dirname, '..');

function readAgentRoot() {
  const rec = readJson(paths.agent, null);
  return rec && typeof rec.root === 'string' ? rec : null;
}

// Called by every cli.js command: the last checkout to actually run is the one
// the launcher should use.
function recordAgentRoot(root = AGENT_ROOT) {
  const current = readAgentRoot();
  if (current && current.root === root) return current;
  ensureDirs();
  const rec = { v: 1, root, recorded_at: new Date().toISOString() };
  writeJsonAtomic(paths.agent, rec);
  return rec;
}

// Whether this copy is installed as a Claude Code plugin. Plugin installs are
// managed by Claude Code — their hooks come from hooks/hooks.json and their
// path is not ours to keep stable — so drift checks that assume a checkout
// would report problems that are not real.
function isPluginInstall(root = AGENT_ROOT) {
  return /[/\\]plugins[/\\]cache[/\\]/.test(root);
}

const LAUNCHER = `'use strict';
// Generated by "cli.js autostart" — do not edit.
// Starts the statusline watcher from wherever the agent currently lives, so a
// plugin update (new versioned directory) or a moved checkout does not strand
// the logon task. Regenerate with: node <agent>/src/cli.js autostart
const fs = require('fs');
const path = require('path');

const record = path.join(__dirname, 'agent.json');
let root;
try {
  root = JSON.parse(fs.readFileSync(record, 'utf8')).root;
} catch (e) {
  console.error('statusline: cannot read ' + record + ' (' + e.message + ') — run "cli.js autostart" again');
  process.exit(1);
}
const cli = path.join(root, 'src', 'cli.js');
if (!fs.existsSync(cli)) {
  console.error('statusline: the recorded agent is gone (' + cli + ') — reinstall, or run "cli.js autostart" from the current copy');
  process.exit(1);
}
process.argv = [process.argv[0], cli, 'start'];
require(cli);
`;

// The one path autostart is allowed to embed: it lives in the data dir, which
// never moves.
function writeLauncher() {
  ensureDirs();
  fs.writeFileSync(paths.launcher, LAUNCHER);
  return paths.launcher;
}

module.exports = { AGENT_ROOT, readAgentRoot, recordAgentRoot, isPluginInstall, writeLauncher };
